spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/forwork?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: zhang1998


server:
  port: 8084